# Generated by Django 5.2.4 on 2025-08-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('cnpj_basico', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('razao_social', models.CharField(db_index=True, max_length=255)),
                ('natureza_juridica', models.CharField(max_length=4)),
                ('qualificacao_responsavel', models.IntegerField()),
                ('capital_social', models.DecimalField(decimal_places=2, max_digits=16)),
                ('porte_empresa', models.CharField(blank=True, max_length=2, null=True)),
                ('ente_federativo_responsavel', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
